app/models.py
from flask_sqlalchemy import SQLAlchemy
from app import db
from sqlalchemy import String

class User(db.Model):
    id =db.Column(db.Integer,primary_key=True)
    username=db.Column(db.String(150),unique=True,nullable=False)
    password=db.Column(db.String(200),nullable=False)

class Task(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    status = db.Column(db.String(20), default='pending')
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'),nullable=False)

    user = db.relationship('User', backref='tasks')

app/__init__.py
from flask import Flask

from flask_sqlalchemy import SQLAlchemy

#create database object globally
db = SQLAlchemy()


def create_app():
    app=Flask(__name__)
    
    app.config['SECRET_KEY']='secret-chabi'
    app.config['SQLALCHEMY_DATABASE_URI']= 'sqlite:///todo.db'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS']=False
    
    
    db.init_app(app)
    
    from app.routes.auth import auth_bp
    from app.routes.tasks import task_bp
    app.register_blueprint(auth_bp)
    app.register_blueprint(task_bp)
    
    return app
    

app/routes/auth.py
from flask import Blueprint ,render_template , redirect ,url_for,request,flash ,session
from werkzeug.security import generate_password_hash, check_password_hash
from app.models import db, User
auth_bp =Blueprint('auth',__name__)




@auth_bp.route('/login',methods=["GET","POST"])
def login():
    if request.method=="POST":
        username=request.form.get('username')
        password=request.form.get('password')
        
        user = User.query.filter_by(username=username).first()
        
        
        if user and check_password_hash(user.password,password):
            session['user_id']=user.id
            session['user'] = user.username
            flash('Login successful' ,'success')
            return redirect(url_for('tasks.view_tasks'))
        else:
            flash('invalid username or password' ,'error')
            
            
    return render_template('login.html')
        

        
@auth_bp.route('/logout')
def logout():
    session.pop('user_id',None)
    flash('logged out','info')
    return redirect(url_for('auth.login'))
        
@auth_bp.route('/register',methods=["GET","POST"])
def register():
    if request.method=="POST":
        username=request.form.get('username')
        password=request.form.get('password')
        
        if username and password:
            existing_user=User.query.filter_by(username=username).first()
            if existing_user:
                flash("username already exists" ,"warning")
                return redirect(url_for('auth.register'))
            
            hashed_password = generate_password_hash(password)
            new_user=User(username=username,password=hashed_password)
            db.session.add(new_user)
            db.session.commit()
            
            flash("Registration successfull Please login","success")
            return redirect(url_for('auth.login'))
        else:
            flash("Please fill all fields","error")
    
    return render_template('register.html')
        
   

app/routes/tasks.py
from flask import Blueprint ,render_template ,url_for,session,redirect,flash,request
from app import db
from app.models import Task


task_bp =Blueprint('tasks',__name__)

@task_bp.route('/')
def view_tasks():
    if 'user_id' not in session:
        flash("Please login to view your tasks", "warning")
        return redirect(url_for('auth.login'))

    user_id = session['user_id']
    tasks = Task.query.filter_by(user_id=user_id).all()
    print("Fetched tasks:", tasks)# Only current user's tasks
    return render_template('tasks.html', tasks=tasks)

@task_bp.route('/add',methods=["POST"])
def add_task():
    if 'user_id' not in session:
        flash("please login first ","warning")
        return redirect(url_for('auth.login'))
    
    title =request.form.get('title')
    if title:
        task =Task(title=title,user_id=session['user_id'])
        db.session.add(task)
        db.session.commit()
        print("Task added:", title)
        flash('Task Added Succesfully','success')
        print("Task added:", title)

    return redirect(url_for('tasks.view_tasks'))


@task_bp.route('/delete/<int:task_id>')
def delete_task(task_id):
    if 'user_id' not in session:
        flash("Login required", "warning")
        return redirect(url_for('auth.login'))

    task = Task.query.get_or_404(task_id)
    if task.user_id != session['user_id']:
        flash("Unauthorized to delete this task", "danger")
        return redirect(url_for('tasks.view_tasks'))

    db.session.delete(task)
    db.session.commit()
    flash("Task deleted successfully", "info")
    return redirect(url_for('tasks.view_tasks'))

@task_bp.route('/toggle/<int:task_id>', methods=["POST"])
def toggle_status(task_id):
    if 'user_id' not in session:
        flash("Login required", "warning")
        return redirect(url_for('auth.login'))

    task = Task.query.get_or_404(task_id)
    if task.user_id != session['user_id']:
        flash("You cannot modify others' tasks", "danger")
        return redirect(url_for('tasks.view_tasks'))

    if task.status == 'pending':
        task.status = 'working'
    elif task.status == 'working':
        task.status = 'done'
    else:
        task.status = 'pending'

    db.session.commit()
    return redirect(url_for('tasks.view_tasks'))


@task_bp.route('/clear',methods=["POST"])
def clear_tasks():
    if 'user_id' not in session:
        flash("Login required", "warning")
        return redirect(url_for('auth.login'))

    Task.query.filter_by(user_id=session['user_id']).delete()
    db.session.commit()
    flash("All your tasks cleared", "info")
    return redirect(url_for('tasks.view_tasks'))    
    

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%} MY TO DO APP {%endblock%}</title>
    <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">
   
   

</head>
<body>
    <header>
        <div class="container">
            <h1>MY TO DO APP</h1>
            <nav>
                <a href="{{url_for('tasks.view_tasks')}}">Home</a>
                {% if 'user_id' in session %}
                <a href ="{{url_for('auth.logout')}}">Logout</a>
                {% else %}
                <a href="{{url_for('auth.login')}}">Login</a>
                <a href="{{url_for('auth.register')}}">Register</a>
              
                
                {% endif%}
            </nav>
        </div>
    </header>
    
    <main class="container">
        {% with messages =get_flashed_messages(with_categories =True)%}
            {% for category ,message in messages%}
                <div class="flash {{category}}"> {{message}}</div>
            {% endfor%}

        {% endwith%}

        {% block content%} {% endblock%}
    </main>

    <footer>
        <div class="container">
            <p>&copy; {{2025}} My To Do App</p>
        </div>
    </footer>
</body>
</html>

app/templates/login.html
{% extends "base.html"%}
{% block title %}Login{% endblock%}

{% block content%} 
<div class="login-box">
    <h2>Login</h2>
    <form method="POST">
       <div class="form-group">
        <label for='username'>Username:</label>
        <input type="text" name="username" id="username" required>
       </div> 

       <div class="form-group">
        <label for='password'>Password:</label>
        <input type="password" name="password" id="password" required>
       </div>
       <button type="submit" class="btn">Login</button> 

    </form>
    

</div>
{% endblock%}

app/templates/register.html
{% extends "base.html" %}
{% block title %}Registration{% endblock%}
{% block content%}
<div class="login-box">
    <h2>Registration</h2>
    <form method="post">
        <div class="form-group">
            <label for="username">Username:</label>
            <input type="text" id="username" name="username" required>
        </div>

        <div class="form-group">
            <label for="password">Password:</label>
            <input type="password" id="password" name="password" required>
        </div>
        <button type="submit" class="btn">Register</button>
    </form>

</div>


{% endblock%}

app/templates/tasks.html
{% extends "base.html" %}
{% block title %}Tasks{% endblock %}

{% block content %}
<div class="task-box">
    <h2>YOUR TASKS</h2>

    <!-- Add Task Form -->
    <form action="{{ url_for('tasks.add_task') }}" method="POST" class="task-form">
        <input type="text" name="title" placeholder="New task" required>
        <button type="submit" class="btn">Add</button>
    </form>

    {% if tasks %}
    <!-- Clear All Tasks -->
    <form method="POST" action="{{ url_for('tasks.clear_tasks') }}">
        <button type="submit" class="btn btn-clear">Clear All Tasks</button>
    </form>
    <br>

    <!-- Task Table -->
    <table class="task-table">
        <thead>
            <tr>
                <th>No.</th>
                <th>Title</th>
                <th>Status</th>
                <th>Change</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for task in tasks %}
            <tr>
                <td>{{ loop.index }}</td>
                <td>{{ task.title }}</td>
                <td>
                    <span class="badge {{ task.status|lower }}">{{ task.status }}</span>
                </td>
                <td>
                    <form action="{{ url_for('tasks.toggle_status', task_id=task.id) }}" method="POST">
                        <button type="submit" class="btn-small">Next</button>
                    </form>
                </td>
                <td>
                    <a href="{{ url_for('tasks.delete_task', task_id=task.id) }}" class="btn-small btn-danger">Delete</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>No tasks yet. Add one above.</p>
    {% endif %}

    <br>

    
</div>
{% endblock %}